---
# Aptitude is required to upgrade the system through ansible (aptitude safe-upgrade)
- name: install aptitude (Required by ansible)
  apt: name=aptitude state=present

- include: hostname.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
- include: users.yml
- include: multiverse_repo.yml
- include: essentials.yml
- include: openntpd.yml
- include: timezone.yml
- include: vim.yml
- include: emacs.yml
- include: ssmtp.yml
- include: fail2ban.yml
- include: sec_updates.yml
- include: ufw.yml
- include: htop.yml
- include: python_setuptools.yml

- name: update apt cache
  apt: update_cache=yes

- name: install required packages
  apt: name={{ item }} state=present
  with_items:
    - gcc
    - make
    - git
    - libpcre3-dev
    - openssl
    - libssl-dev
    - rsync
