---
 # Tasks that will configure openntpd.

 - name: Openntpd | Ensure "openntpd" is at the latest version
   apt: name=openntpd state=latest update_cache=true

 - name: Openntpd | Ensure "openntpd" is started
   service: name=openntpd state=started enabled=yes
